"""add user account status

Revision ID: 35954f942dcc
Revises: ad74462c9a16
Create Date: 2026-09-15 20:51:03.151289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35954f942dcc'
down_revision: Union[str, Sequence[str], None] = 'ad74462c9a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='userstatus'), nullable=False,server_default='ACTIVE'))
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
